import pandas as pd

df = pd.read_csv(r"C:\DAV PROGRAM\employee_salary_dataset.csv")

print(df.tail())
print("\n")
print(df.head())
print("\n")
print(df['salary'].dtype)
print("\n")
print(df['gender'])
print("\n")
print(df[['gender','salary']])
print("\n")
df_rank = df.groupby('rank').mean(numeric_only=True)
print(df_rank)
print("\n")
print(df.groupby('rank')[['salary']].mean())
print("\n")
df_sub = df[df['salary'] > 120000]
print(df_sub)
print("\n")
df_f = df[df['gender'] == 'Female']
print(df_f)
print("\n")
print(df['salary'])
print("\n")
print(df[['rank','salary']])
print("\n")
print(df[4:9])
print("\n")
print(df.loc[1:10, ['rank','gender','salary']])
print("\n")
print(df.iloc[1:10,[0,1,3]])
print("\n")
print(df.iloc[0])
i=2;
print(df.iloc[i])
print("\n")
print(df.iloc[-1])
print("\n")
print(df.iloc[0:7])
print("\n")
print("\n")
print(df.iloc[:,0:2])
print("\n")
print(df.iloc[1:3,0:2])
print("\n")
print(df.iloc[[0,5],[1,3]])
print("\n")
df_sorted=df.sort_values(by='service')
print(df_sorted.head())

df_sorted = df.sort_values(by=['service', 'salary', 'Price'], ascending=[False, False, False])
print(df_sorted.head(10))